PAIR-code/deliberate-lab

scripts/src/seed-database.ts, utils/src/types/stages.types.ts, utils/src/validation/experiments.validation.ts, utils/src/validation/stages.validation.ts, webapp/src/app/app-home/app-home.component.html, webapp/src/app/app.module.ts, webapp/src/app/experimenter-view/create-experiment/create-experiment.component.html, webapp/src/app/experimenter-view/create-experiment/create-experiment.component.scss, webapp/src/app/experimenter-view/create-experiment/create-experiment.component.ts, webapp/src/app/experimenter-view/experiment-monitor/experiment-monitor.component.html, webapp/src/app/participant-view/participant-stage-view/exp-chat/chat-user-profile/chat-user-profile.component.html, webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.html, webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.scss, webapp/src/app/participant-view/participant-stage-view/exp-info/exp-info.component.html, webapp/src/app/participant-view/participant-stage-view/exp-info/exp-info.component.scss, webapp/src/app/participant-view/participant-stage-view/exp-info/exp-info.component.spec.ts, webapp/src/app/participant-view/participant-stage-view/exp-info/exp-info.component.ts, webapp/src/app/participant-view/participant-stage-view/exp-profile/exp-profile.component.html, webapp/src/app/participant-view/participant-stage-view/participant-stage-view.component.html, webapp/src/app/participant-view/participant-stage-view/participant-stage-view.component.ts, webapp/src/app/participant-view/participant-view.component.html, webapp/src/index.html
This PR includes:
* Adding an "information" component feature.
* Updating the default experiment and template to include information context.
* Cleaned up chat interface.
* Slight formatting and language changes.
Fixes #16 and #15 .
(Apologies for not breaking this into multiple commits!)
=> Rewrite the Adrift in the Atlantic task.

functions/package-lock.json, functions/package.json, functions/predeploy.sh, functions/src/endpoints/participants.endpoints.ts, utils/src/utils/cache.utils.ts, webapp/src/app/experimenter-view/experiment-monitor/experiment-monitor.component.ts, webapp/src/app/experimenter-view/experimenter-view.component.ts, webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.ts, webapp/src/app/participant-view/participant-stage-view/exp-leader-reveal/exp-leader-reveal.component.html, webapp/src/app/participant-view/participant-stage-view/exp-survey/exp-survey.component.ts, webapp/src/lib/utils/angular.utils.ts
=> Second batch of bug fixes for the playtest

functions/src/triggers/chats.triggers.ts, functions/src/triggers/stages.triggers.ts, utils/src/types/chats.types.ts, utils/src/types/questions.types.ts, utils/src/validation/questions.validation.ts, webapp/src/app/components/bottom-scroll-list/bottom-scroll-list.component.html, webapp/src/app/components/bottom-scroll-list/bottom-scroll-list.component.scss, webapp/src/app/components/bottom-scroll-list/bottom-scroll-list.component.spec.ts, webapp/src/app/components/bottom-scroll-list/bottom-scroll-list.component.ts, webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.html, webapp/src/app/participant-view/participant-stage-view/exp-chat/exp-chat.component.ts, webapp/src/app/participant-view/participant-stage-view/exp-survey/survey-rating-question/survey-rating-question.component.html
=> Playtest Bug Fixes v3

functions/src/endpoints/experiments.endpoints.ts, lit/README.md, lit/package.json, lit/src/experiment-components/chat/lost_at_sea_chat.ts, lit/src/experiment-components/footer/footer.ts, lit/src/experiment-components/modules/election/election_preview.ts, lit/src/experiment-components/survey/survey_preview.ts, lit/src/services/firebase_service.ts, lit/src/services/participant_service.ts, utils/src/types/participants.types.ts
=> Issue fixes before the 25-06-2024 playtest

lit/package-lock.json, lit/package.json, lit/src/experiment-components/chat/chat_interface.scss, lit/src/experiment-components/chat/chat_interface.ts, lit/src/experiment-components/chat/chat_message.scss, lit/src/experiment-components/chat/lost_at_sea_chat.ts, lit/tsconfig.json
In chat left side panel,
Fixes #75
=> Fix chat side panel styling

docs/getting-started.md, functions/src/triggers/chats.triggers.ts, lit/src/experiment-components/experiment/experiment_config.ts, lit/src/experiment-components/info/info_config.ts, lit/src/experiment-components/info/info_preview.scss, lit/src/experiment-components/info/info_preview.ts, lit/src/experiment-components/modules/election/election_preview.scss, lit/src/experiment-components/modules/election/election_preview.ts, lit/src/experiment-components/modules/election/election_reveal.scss, lit/src/experiment-components/modules/election/election_reveal.ts, lit/src/experiment-components/profile/profile_preview.ts, lit/src/experiment-components/survey/survey_config.ts, lit/src/experiment-components/survey/survey_preview.scss, lit/src/experiment-components/survey/survey_preview.ts, lit/src/experiment-components/tos/tos_config.ts, lit/src/experiment-components/tos/tos_preview.scss, lit/src/experiment-components/tos/tos_preview.ts, lit/src/services/config/experiment_config_service.ts, lit/src/services/config/info_config_service.ts, lit/src/services/config/survey_config_service.ts, lit/src/services/config/tos_config_service.ts, lit/src/shared/constants.ts, lit/src/shared/lost_at_sea_constants.ts, lit/src/shared/utils.ts, scripts/src/seed-database.ts, utils/src/types/stages.types.ts, utils/src/validation/stages.validation.ts
Fixes #21 
Adds a description field (currently active on Info, TOS and Survey Stages).
Update the "LAS module" descriptors.
=> Add a description field and update the LAS  module.

functions/src/endpoints/experiments.endpoints.ts, functions/src/utils/validation.ts, utils/src/validation/stages.validation.ts
Improve validation errors reporting by discriminating typebox Union errors using the `kind` field
=> Better validation errors

lit/src/experiment-components/chat/lost_at_sea_chat.scss, lit/src/experiment-components/experiment/experiment_config.ts, lit/src/sass/_common.scss, lit/src/services/config/experiment_config_service.ts, utils/src/validation/stages.validation.ts
=> Add stage validation for experiment creation, improve labeling for experiment groups, resize chat window.

lit/src/components/experiment_group/experiment_group.ts, lit/src/services/config/experiment_config_service.ts, utils/src/types/stages.types.ts, utils/src/validation/stages.validation.ts
* Navigate to home upon group deletion.
* Add validation for group names.
* Fix BaseStageConfig and stage validation compile errors.
=> Fix a few bugs / minor improvements.

functions/src/endpoints/experiments.endpoints.ts, functions/src/endpoints/participants.endpoints.ts, lit/src/app.ts, lit/src/components/header/header.ts, lit/src/components/landing/experiment_group.ts, lit/src/experiment-components/experiment/experiment_config_actions.ts, lit/src/experiment-components/experiment/experiment_config_menu.scss, lit/src/experiment-components/experiment/experiment_preview.ts, lit/src/experiment-components/footer/footer.ts, lit/src/experiment-components/profile/profile_preview.scss, lit/src/experiment-components/profile/profile_preview.ts, lit/src/services/config/experiment_config_service.ts, lit/src/services/experiment_service.ts, lit/src/services/experimenter_service.ts, lit/src/shared/callables.ts, utils/src/types/experiments.types.ts, utils/src/types/participants.types.ts, utils/src/validation/experiments.validation.ts
=> Implement dynamic lobbies MVP.

functions/src/endpoints/experiments.endpoints.ts, lit/src/app.ts, lit/src/components/landing/experiment_card.ts, lit/src/experiment-components/experiment/experiment_config_metadata.ts, lit/src/experiment-components/profile/profile_preview.ts, lit/src/services/config/experiment_config_service.ts, lit/src/services/experiment_service.ts, lit/src/services/experimenter_service.ts, utils/src/types/experiments.types.ts, utils/src/validation/experiments.validation.ts
* Fix rendering progress bar in groups
* Add an option to wait for all participants to join when nMaxParticipants specified (checkbox in experiment config)
* Add relevant properties to transfer dashboard
Feel free to merge if it looks good!
=> Make small group experiment UX changes

functions/src/endpoints/experiments.endpoints.ts, lit/src/app.ts, lit/src/experiment-components/experiment/experiment_config_menu.ts, lit/src/experiment-components/experiment/experiment_config_metadata.ts, lit/src/experiment-components/experiment/experiment_preview.ts, lit/src/experiment-components/footer/footer.ts, lit/src/experiment-components/survey/survey_config.ts, lit/src/experiment-components/survey/survey_preview.ts, lit/src/service_provider.ts, lit/src/services/config/experiment_config_service.ts, lit/src/services/experimenter_service.ts, lit/src/services/survey_service.ts, lit/src/shared/lost_at_sea/constants.ts, lit/src/shared/lost_at_sea/utils.ts, lit/src/shared/utils.ts, utils/src/validation/experiments.validation.ts, utils/src/validation/questions.validation.ts
=> Update latest instructions and limit transfers to max experiments.

lit/src/app.ts, lit/src/experiment-components/attention_check/attention_check_popup.scss, lit/src/experiment-components/attention_check/attention_check_popup.ts, lit/src/shared/lost_at_sea/constants.ts, lit/src/shared/lost_at_sea/utils.ts
Note: Will refactor styling later.
=> Render mediation panel for chat outside of participant view

functions/src/endpoints/experiments.endpoints.ts, functions/src/triggers/stages.triggers.ts, lit/src/app.ts, lit/src/components/landing/experiment_card.ts, lit/src/experiment-components/attention_check/attention_check_popup.ts, lit/src/experiment-components/chat/chat_interface.ts, lit/src/experiment-components/chat/lost_at_sea_chat.ts, lit/src/experiment-components/election/election_preview.ts, lit/src/experiment-components/experiment/experiment_config_menu.ts, lit/src/experiment-components/experiment/experiment_config_metadata.ts, lit/src/experiment-components/experiment/experiment_preview.ts, lit/src/experiment-components/footer/footer.ts, lit/src/experiment-components/profile/profile_avatar.scss, lit/src/experiment-components/profile/profile_avatar.ts, lit/src/experiment-components/profile/profile_preview.ts, lit/src/experiment-components/progress/progress_end_chat.ts, lit/src/experiment-components/progress/progress_stage_completed.ts, lit/src/experiment-components/progress/progress_stage_waiting.ts, lit/src/services/chat_service.ts, lit/src/services/config/experiment_config_service.ts, lit/src/services/experiment_service.ts, lit/src/services/experimenter_service.ts, lit/src/shared/lost_at_sea/constants.ts, lit/src/shared/lost_at_sea/utils.ts, utils/src/types/experiments.types.ts, utils/src/validation/experiments.validation.ts
Fixes #176 #194 
* Fix dropout; allow progression of chat (inactive profiles are passed through) and hiding of inactive profiles from elections.
* Add parameterized lobby configuration with optional lobby wait time
=> Handle dropout properly and add configurable lobby wait time

frontend/src/components/experiment_manager/participant_summary.ts, frontend/src/components/header/header.ts, frontend/src/components/popup/booted_popup.ts, frontend/src/components/stages/transfer_view.ts, frontend/src/services/experiment.editor.ts, frontend/src/shared/participant.utils.ts, utils/src/stages/transfer_stage.ts, utils/src/utils/algebraic.utils.ts
=> Fix lobby countdown logic, add boot participant confirmation, and improve experiment creation redirect.

frontend/src/components/experiment_builder/experiment_settings_editor.scss, frontend/src/components/experiment_builder/experiment_settings_editor.ts, frontend/src/components/header/header.ts, frontend/src/components/stages/chat_interface.ts, frontend/src/components/stages/ranking_editor.scss, frontend/src/components/stages/ranking_editor.ts, frontend/src/components/stages/ranking_reveal_view.scss, frontend/src/components/stages/ranking_reveal_view.ts, frontend/src/components/stages/survey_reveal_view.ts
Minus one (re: waiting on reveal stage dependencies), which we can file as a bug.
=> Fix all unclaimed bugs from the previous deployment playtest.

frontend/src/components/experiment_manager/cohort_summary.scss, frontend/src/components/participant_previewer/participant_previewer.scss, frontend/src/components/popup/accept_transfer_popup.ts, frontend/src/components/progress/progress_stage_waiting.ts, frontend/src/components/stages/chat_interface.ts, frontend/src/components/stages/chat_panel.scss, frontend/src/services/participant.answer.ts, frontend/src/services/participant.service.ts
- Fixes refresh/syncing bugs: #319 #320
- Fix overflow scrolling for cohort summary participant list, chat panel participant/agent list
=> Fix refresh/syncing bugs, scrolling bugs

frontend/src/components/experiment_manager/cohort_settings_dialog.ts, frontend/src/components/experiment_manager/experiment_manager_nav.ts, frontend/src/components/header/header.ts, frontend/src/components/participant_previewer/participant_previewer.ts, frontend/src/components/participant_profile/profile_preview.ts, frontend/src/components/progress/progress_stage_waiting.ts, frontend/src/components/stages/chat_interface.ts, frontend/src/services/cohort.service.ts, frontend/src/services/experiment.manager.ts, frontend/src/services/participant.service.ts, frontend/src/shared/callables.ts, frontend/src/shared/participant.utils.ts, functions/src/cohort.endpoints.ts, utils/src/cohort.ts, utils/src/cohort.validation.ts, utils/src/experiment.ts, utils/src/participant.ts, utils/src/participant.validation.ts
- Refactor waiting function to correctly calculate whether or not to remain on waiting screen
- Render wait stage message in experimenter-only banner
- Fix bug with overriding cohort public stage data
- Fix #335 using new participant "waiting phase completed" timestamps logic
=> Fix participant waiting screen bugs

firestore/storage.rules, frontend/src/components/experiment_builder/experiment_settings_editor.ts, frontend/src/components/experiment_manager/participant_summary.ts, frontend/src/components/participant_previewer/participant_previewer.ts, frontend/src/components/popup/attention_check_popup.ts, frontend/src/components/stages/ranking_reveal_view.ts, frontend/src/components/stages/survey_view.scss, frontend/src/components/stages/survey_view.ts, frontend/src/sass/_common.scss, frontend/src/services/analytics.service.ts, frontend/src/services/experiment.editor.ts, frontend/src/services/experiment.manager.ts, frontend/src/services/participant.service.ts, frontend/src/shared/participant.utils.ts, utils/src/experiment.ts, utils/src/experiment.validation.ts, utils/src/participant.ts, utils/src/participant.validation.ts
* Signal unfilled-out survey fields that are required.
* Fix reveal logic in ranking reveal.
=> Add survey fields required indicator and fix ranking reveal rendering bug

frontend/src/components/participant_previewer/participant_header.scss, frontend/src/components/participant_previewer/participant_header.ts, frontend/src/components/participant_previewer/participant_previewer.ts, frontend/src/components/progress/progress_stage_waiting.scss, frontend/src/components/progress/progress_stage_waiting.ts, frontend/src/components/stages/chip_participant_view.ts, frontend/src/components/stages/chip_reveal_view.scss, frontend/src/services/participant.service.ts, frontend/src/shared/games/chip_negotiation.ts, functions/src/stages/chip.endpoints.ts
Fix chip negotiation game usability issues based on 2024-12-11 playtest.
=> Improve UX for chip negotiation game

frontend/src/components/experimenter/experimenter_manual_chat.ts, frontend/src/components/experimenter/experimenter_panel.scss, frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/components/stages/chat_editor.scss, frontend/src/components/stages/chat_editor.ts, frontend/src/components/stages/chat_message.ts, frontend/src/components/stages/chat_panel.ts, frontend/src/service_provider.ts, frontend/src/services/agent.editor.ts, frontend/src/services/experiment.manager.ts, frontend/src/services/experiment.service.ts, frontend/src/shared/callables.ts, frontend/src/shared/constants.ts, frontend/src/shared/games/reality_tv_chat.ts, functions/src/stages/chat.endpoints.ts, functions/src/stages/chat.triggers.ts, utils/src/experiment.ts, utils/src/shared.ts, utils/src/stages/chat_stage.ts, utils/src/stages/chat_stage.validation.ts
=> Implement WPM and probabilistic sampling for agent responses; also rename mediators to agents.

frontend/src/components/stages/chip_participant_view.ts, frontend/src/components/stages/chip_reveal_view.ts, frontend/src/components/stages/chip_view.scss, frontend/src/components/stages/payout_editor.ts, frontend/src/components/stages/payout_summary_view.ts, frontend/src/shared/games/chip_negotiation.ts, utils/src/experiment.ts, utils/src/stages/chip_stage.ts, utils/src/stages/chip_stage.validation.ts, utils/src/stages/payout_stage.ts
=> Fix chip negotiation payout/offer calculations and hardcoded chip values

frontend/src/components/stages/chat_message.ts, frontend/src/components/stages/chat_panel.ts, frontend/src/services/experiment.manager.ts, functions/src/stages/chat.triggers.ts, utils/src/stages/chat_stage.ts
* Surface stage details (e.g. description) in agent prompt 
* Render agents as participants (with agent differentiation visible in debug mode)
=> Add agent improvements from EDU conversation.

frontend/src/components/participant_previewer/participant_previewer.ts, frontend/src/components/stages/comprehension_participant_view.ts, frontend/src/components/stages/comprehension_view.scss, frontend/src/services/experiment.manager.ts, frontend/src/services/participant.answer.ts, frontend/src/shared/file.utils.ts, frontend/src/shared/games/chip_negotiation.ts, functions/src/cohort.endpoints.ts, functions/src/experiment.endpoints.ts, utils/src/index.ts, utils/src/stages/comprehension_stage.ts, utils/src/stages/comprehension_stage.validation.ts, utils/src/stages/stage.ts, utils/src/stages/stage.validation.ts
=> Update data download and add comprehension stage

frontend/src/shared/games/chip_negotiation.ts
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.
=> updating instructions a bit, proofreading and editing.

frontend/src/services/experiment.manager.ts, frontend/src/shared/file.utils.ts
This also includes a general enhancement (adding columns for player name, avatar, pronouns in the main CSV).
=> Add chip negotiation data download enhancements

frontend/src/components/experiment_manager/experiment_manager_nav.ts, frontend/src/shared/games/chip_negotiation.ts
=> Make small negotiation-related fixes

frontend/src/services/experiment.manager.ts, frontend/src/shared/file.utils.ts, frontend/src/shared/utils.ts
=> Correct timestamp formatting to ISO-style and download a zipped file of experiment contents. 

frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/services/cohort.service.ts, functions/src/experiment.endpoints.ts, functions/src/index.ts, functions/src/stages/chat.endpoints.ts, functions/src/stages/chat.triggers.ts, functions/src/stages/chat.utils.ts, utils/src/experiment.ts, utils/src/stages/chat_stage.ts, utils/src/stages/stage.ts
Fixes #399 #357 
This also refactors some /function utils.
=> Update cohort logic to fix completed/ready to end bugs

frontend/src/components/admin/admin_dashboard.ts, frontend/src/components/experiment_dashboard/experiment_dashboard.scss, frontend/src/components/experiment_dashboard/experiment_dashboard.ts, frontend/src/components/experimenter/experimenter_manual_chat.ts, frontend/src/components/experimenter/experimenter_panel.scss, frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/components/participant_profile/profile_display.ts, frontend/src/components/participant_view/participant_view.ts, frontend/src/components/stages/chat_editor.ts, frontend/src/components/stages/chat_message.ts, frontend/src/components/stages/chat_panel.ts, frontend/src/shared/utils.ts
Fixes #256 #437 #436 #440
Frontend-only changes.
=> Make minor updates to experimenter dashboard UX and fix participant view bugs

functions/src/agent.utils.ts
This was accidentally left in after #392.
=> Remove OPENAI_BASE_URL environment override.

README.md
=> Point README to new docs

functions/src/agent.utils.ts
We had some wrong variable names here. We should write some tests for this file, but I ran out of time for it today.
=> Read model name correctly in getAgentResponse.

functions/src/agent.endpoints.ts, functions/src/agent.utils.ts, functions/src/api/gemini.api.test.ts, functions/src/api/gemini.api.ts, functions/src/api/model.response.ts, functions/src/api/ollama.api.ts, functions/src/api/openai.api.test.ts, functions/src/api/openai.api.ts, functions/src/stages/chat.triggers.ts, functions/src/stages/chat.utils.ts, functions/src/stages/ranking.utils.ts, functions/src/stages/survey.utils.ts
Depends on #510, and extends its changes to the OpenAI/compatible API.
=> Return detailed output from OpenAI/compatible API.

utils/src/stages/survey_stage.validation.ts
Missed updating this file in #546.
=> Fix survey validation

functions/src/api/gemini.api.ts, functions/src/api/openai.api.ts
=> Fix PR #557 bug with checking structured output config in API functions

frontend/src/components/stages/asset_allocation_editor.ts, frontend/src/components/stages/asset_allocation_participant_view.ts, frontend/src/components/stages/stockinfo_editor.ts, frontend/src/components/stages/stockinfo_participant_view.ts, frontend/src/services/participant.answer.ts, frontend/src/shared/templates/asset_allocation_template.ts, frontend/src/shared/templates/stockinfo_template.ts, functions/src/prompt.utils.ts, functions/src/stages/asset_allocation.utils.ts, functions/src/utils/firestore.ts, utils/src/stages/asset_allocation_stage.ts, utils/src/stages/asset_allocation_stage.utils.ts, utils/src/stages/asset_allocation_stage.validation.ts, utils/src/stages/stockinfo_stage.ts, utils/src/stages/stockinfo_stage.utils.ts, utils/src/stages/stockinfo_stage.validation.ts
Refactored StockInfo and AssetAllocation stages to make their state / answer logic a bit simpler (which made it easier to add prompt.utils methods for them both).
=> Add chat prompt context for AssetAllocation stage

.github/workflows/ci.yaml
Testing this on a local Docker runner (via `act`), it successfully finds some test failures and format errors. We may need some more config on Github's side to configure a runner, and to block merges once the test and format problems are fixed.
For now, this doesn't build the frontend, since I couldn't get that working from the runner without a firebase login.
=> Add workflow to automatically check format and run tests.

frontend/src/shared/templates/chip_negotiation.ts, utils/src/stages/chip_stage.prompts.ts
1. fix instruction in IRB for the chip-pilot
2.fix advisor response in chip-pilot
=> fix instruction in IRB and advisor response

frontend/src/shared/templates/chip_negotiation.ts
1. fix the time spent in the introduction for the chip-pilot branch
=> Update the time estimate in chip negotiation template terms of service

functions/src/api/gemini.api.test.ts, functions/src/api/gemini.api.ts, functions/src/api/openai.api.test.ts, functions/src/api/openai.api.ts, utils/src/structured_output.test.ts, utils/src/structured_output.ts
Add support for enum-valued structured output fields. This is backend only, no UI support.
=> Add enum support to structured outputs.

functions/package-lock.json, functions/package.json, functions/src/app.ts, functions/src/log.utils.test.ts
We end up with some undefined properties in the object. Set firestore to ignore them.
Fixes #611.
=> Fix logging when structured output json_schema mode is enabled.

frontend/src/components/experiment_builder/agent_chat_prompt_editor.ts, functions/src/chat/chat.agent.ts
Allow deleting shouldRespond in editor (and add failsafes for other values if deleted).
=> Add failsafes for core schema fields (shouldRespond, readyToEndChat, etc.)

frontend/src/components/experiment_builder/stage_builder_dialog.ts, frontend/src/shared/templates/policy.ts
Depends on #661 (and also #660).
=> Add Policy experiment template.

frontend/src/components/experiment_builder/agent_chat_prompt_editor.ts, functions/src/agent.utils.ts, functions/src/api/gemini.api.ts, functions/src/api/ollama.api.ts, functions/src/api/openai.api.ts, functions/src/chat/chat.agent.ts, functions/src/chat/message_converter.utils.ts, utils/src/agent.ts
=> Enable disabling of safety filters for Gemini API.

frontend/src/components/experiment_builder/stage_builder_dialog.ts
=> Move comprehension stage to "Other stages" in stage dialog builder

functions/src/api/gemini.api.ts
Fixes issue introduced in #671.
=> Fix safetySettings (HARM_CATEGORY_CIVIC_INTEGRITY is deprecated).

functions/src/triggers/chat.triggers.ts
* Replaced forEach with Promise.all in Firestore triggers to properly await async operations
* This has removed the mysterious delays (caused by functions returning before their async work completed?). 
* Chat triggers now execute within ~1 second as Firebase properly tracks function completion, preventing the orphaned background operations that were causing unpredictable delays.
Potential other chat optimizations to look into:
* Batched writes?
* Simplify duplicate message checks (e.g. when we know it's just one agent mediator & one participant).
=> Fix issue with chatMessage triggers.

frontend/src/components/experiment_builder/stage_builder_dialog.ts, frontend/src/shared/templates/charity_allocations.ts
Updated:
Order of post-discussion allocation vote and mediator survey
Merged with Vivian's multi-asset allocation feature.
Removed sociological survey questions
added positive / negative questions w.r.t mediator
Likert scale for all survey questions.
TESTED on local deployment.###
=> Charity Surveys pilot round2 update
