docs/getting-started.md, lit/.gitignore, lit/README.md, lit/package-lock.json, lit/package.json, lit/src/app.ts, lit/src/experiment-components/chat/chat_message.scss, lit/src/experiment-components/chat/chat_message.ts, lit/src/experiment-components/survey/survey_preview.ts, lit/src/service_provider.ts, lit/src/services/chat_service.ts, lit/src/services/firebase_service.ts, lit/src/services/llm_service.ts, lit/src/shared/config_example.ts, lit/src/shared/constants.ts, lit/src/shared/prompts.ts, lit/src/shared/types.ts
This sets up ChatService to query the Gemini API for an LLM mediator response after each new chat message and (if no other chat messages have been sent in the meantime) converts that response to a mediator chat message.
> Note: This uses a placeholder prompt, which we'll have to update for real mediation :)
Fixes #51
=> Add LLM service (Gemini API) to frontend

lit/src/components/header/header.scss, lit/src/components/header/header.ts, lit/src/components/landing/experiment_card.scss, lit/src/components/landing/experiment_card.ts, lit/src/components/landing/experiment_group.ts, lit/src/components/landing/experiment_landing.ts, lit/src/components/sidenav/sidenav.ts, lit/src/experiment-components/experiment/experiment_config.scss, lit/src/experiment-components/experiment/experiment_config.ts, lit/src/experiment-components/experiment/experiment_config_actions.scss, lit/src/experiment-components/experiment/experiment_config_actions.ts, lit/src/experiment-components/experiment/experiment_config_metadata.scss, lit/src/experiment-components/experiment/experiment_config_metadata.ts, lit/src/experiment-components/experiment/experiment_config_sidenav.scss, lit/src/experiment-components/experiment/experiment_config_sidenav.ts, lit/src/experiment-components/experiment/experiment_preview.scss, lit/src/experiment-components/experiment/experiment_preview.ts, lit/src/experiment-components/sidenav/sidenav.ts, lit/src/sass/_common.scss, lit/src/services/auth_service.ts, lit/src/services/config/experiment_config_service.ts
- Enable experimenters to set public name, description for experiments
- Refactor metadata config UI
- Only show "delete experiment" buttons when experimenters click to "edit"
- Fix small UX bugs (e.g., flex-shrink, chip height)
- Add small visual cues to frontend (e.g., indicator for lobby stage, experiment selection in sidenav)
=> Update UX for configuring experiment metadata

functions/src/endpoints/experiments.endpoints.ts, functions/src/endpoints/participants.endpoints.ts, lit/src/experiment-components/experiment/experiment_config_actions.ts, lit/src/experiment-components/experiment/experiment_preview.ts, lit/src/experiment-components/footer/footer.ts, lit/src/experiment-components/profile/profile_preview.ts, lit/src/services/config/experiment_config_service.ts, lit/src/services/experiment_service.ts, lit/src/services/experimenter_service.ts, utils/src/types/experiments.types.ts, utils/src/types/participants.types.ts, utils/src/validation/experiments.validation.ts
Changes discussed in #145:
https://github.com/user-attachments/assets/43e329ea-ee39-4e0a-b698-7f6d6b7d85fa
- create/delete functions have been refactored to services instead of UI components
- added isLobby field to experiment
- added transferConfig to experiment to specify the transfer experiment/participant IDs
- added button for participant to self-diretc themselves to the new experiment (once the experimenter has assigned it)
- deleteParticipant function is still present in experimenterService, but not called
- transferred participants are sorted at the bottom of experiment_preview page
Note that the following change has not yet been implemented:
- when creating multi-group (lobby) experiments, start all experiments with 0 participants (as lobby participants will self-join and …
=> Add discussed changes to lobby transfer implementation

frontend/src/components/experiment_builder/experiment_builder.ts, frontend/src/components/experiment_builder/stage_builder_dialog.ts, frontend/src/components/experiment_manager/participant_summary.ts, frontend/src/components/participant_previewer/participant_previewer.ts, frontend/src/components/popup/accept_transfer_popup.ts, frontend/src/components/popup/attention_check_popup.ts, frontend/src/components/stages/transfer_editor.scss, frontend/src/components/stages/transfer_editor.ts, frontend/src/components/stages/transfer_view.scss, frontend/src/components/stages/transfer_view.ts, frontend/src/services/participant.service.ts, utils/src/index.ts, utils/src/stages/stage.ts, utils/src/stages/stage.validation.ts, utils/src/stages/transfer_stage.ts, utils/src/stages/transfer_stage.validation.ts
During a transfer stage, participants wait (no "next stage" click option) for an experimenter to transfer them to a cohort. If a timeout is enabled, participants will be removed from the experiment at the end of the timeout window (which starts when the participant enters the transfer stage).
=> Add transfer stage to experiments

frontend/src/components/progress/progress_stage_waiting.scss, frontend/src/components/progress/progress_stage_waiting.ts, frontend/src/components/stages/base_stage_editor.scss, frontend/src/components/stages/base_stage_editor.ts, frontend/src/components/stages/reveal_editor.ts, frontend/src/components/stages/transfer_view.ts, frontend/src/services/experiment.editor.ts, frontend/src/shared/experiment.utils.ts
Fixes #241 
* Disable editing "Wait for all participants" in reveal stage under specific conditions.
* Only allow revealing preceding stages (#241).
* Get rid of lock overlay on transfer stage.
* Font improvements.
=> Fix playtest issues with stage access, setup

frontend/src/components/experimenter/experimenter_data_editor.ts, frontend/src/components/experimenter/experimenter_panel.scss, frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/components/header/header.ts, frontend/src/components/stages/chat_editor.scss, frontend/src/components/stages/chat_editor.ts, frontend/src/components/stages/chat_message.scss, frontend/src/components/stages/chat_message.ts, frontend/src/components/stages/chat_panel.scss, frontend/src/components/stages/chat_panel.ts, frontend/src/service_provider.ts, frontend/src/services/auth.service.ts, frontend/src/services/experiment.service.ts, frontend/src/services/mediator.editor.ts, frontend/src/shared/callables.ts, functions/src/stages/chat.endpoints.ts, functions/src/stages/chat.triggers.ts, utils/src/stages/chat_stage.ts, utils/src/stages/chat_stage.validation.ts
- Add a "debug" toggle button in experimenter header banner - when it's toggled on, the chat stage shows agents in the panel + explanations underneath LLM mediator messages; when it's off, the chat stage is identical to what participants see
- Add option to turn on "JSON mode" and specify which JSON fields should be used to populate the main chat message (defaults to "response") and explanation (defaults to "explanation")
- Add ability to edit prompt for existing mediators from experimenter right panel (also, add API key configuration editor to same panel)
Fixes #284
=> Add ability to configure JSON and show debugging for mediators

frontend/src/components/experimenter/experimenter_panel.scss, frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/components/stages/chat_editor.scss, frontend/src/components/stages/chat_editor.ts, frontend/src/services/mediator.editor.ts, functions/src/stages/chat.triggers.ts
- Fix bug with parsing mediator responses (wrap parsing in try/catch)
- Allow experimenters to toggle JSON for mediator configs in the experimental panel
- Adjust note on JSON setup in mediator editor (under chat stage editor)
=> Enhance mediator workflow before platform launch

frontend/src/components/header/header.ts, frontend/src/components/stages/chat_editor.scss, frontend/src/components/stages/chat_editor.ts, frontend/src/components/stages/chat_interface.ts, frontend/src/components/stages/chat_message.scss, frontend/src/components/stages/chat_message.ts, frontend/src/components/stages/chat_panel.scss, frontend/src/components/stages/chat_panel.ts, frontend/src/services/mediator.editor.ts, frontend/src/shared/utils.ts, functions/src/stages/chat.endpoints.ts, functions/src/stages/chat.triggers.ts, utils/src/experiment.ts, utils/src/stages/chat_stage.ts, utils/src/stages/chat_stage.validation.ts
Fixes #308.
* Experiment creators can add a "time in minutes" when creating a chat stage.
* Mute mediators is removed: it should not have been created at the experiment level, and was a stop gap for this feature.
* Countdowns are rendered for all participants.
* When the time has elapsed, human and agent participants can no longer respond.
Note: There can be a bit of latency sometimes before the discussion is "ended". I think this is because the "update" logic is awaiting and the mediator typing simulation is also awaiting. These are done in parallel, but there might be some lag.
=> Implement a working timer to the chat stage.

frontend/src/components/experiment_dashboard/experiment_dashboard.ts, frontend/src/services/experiment.manager.ts, frontend/src/shared/callables.ts, functions/src/agent.endpoints.ts, functions/src/agent.utils.ts, functions/src/index.ts, functions/src/stages/chat.triggers.ts, utils/src/agent.validation.ts, utils/src/index.ts, utils/src/stages/ranking_stage.prompts.ts
This allows experimenters to use a frontend button to call an agent participant testing endpoint:
The endpoint then constructs a prompt based on the current stage (TODO: add these prompts! right now it just builds a dummy prompt), sends to API, and console logs the response:
As we complete bugs like #413, we can fill in the TODO area by calling new utils/functions to construct the correct prompt.
=> Add endpoint to test agent participant prompts

frontend/src/components/participant_view/participant_view.ts, frontend/src/components/stages/payout_editor.scss, frontend/src/components/stages/payout_editor.ts, frontend/src/components/stages/payout_participant_view.ts, frontend/src/components/stages/payout_summary_view.ts, frontend/src/components/stages/ranking_editor.scss, frontend/src/components/stages/survey_editor.scss, frontend/src/shared/file.utils.ts, frontend/src/shared/games/chip_negotiation.ts, frontend/src/shared/games/lost_at_sea.ts, frontend/tsconfig.json, functions/src/participant.triggers.ts, utils/src/experiment.ts, utils/src/stages/payout_stage.ts, utils/src/stages/payout_stage.validation.ts, utils/src/stages/stage.ts
Fixes #422 #398 
When configuring payout items, experimenters can assign a "random selection ID" to each item. For each unique "random selection ID," one of the items tagged with that ID is randomly selected (for each participant as the participant profile is created).
> Example: Payout stage includes a payout item "survey-1" and a payout item "survey-2". Both payout items are assigned the random selection ID "survey-payout." When a participant joins the experiment, either survey-1 or survey-2 is selected (randomly), and a resulting map is written to the participant's stage data, e.g., `{ 'survey-payout': 'survey-1' }`. This map is then referenced when determining whether to calculate payout (e.g., if an item has the random selection ID 'survey-payout' but is not 'survey-1', it will not …
=> Enable random selection of payout items (per participant)

frontend/src/components/stages/chat_editor.scss, frontend/src/components/stages/chat_editor.ts
Add a new name-value-input for custom body request fields. Move each numerical sampling parameter into its own number-input div so they're not as wide.
Also set the minimum of the frequency penalty and presence penalty boxes to 0; this makes them equal in width to the others, and it's unlikely that a user would want to set them below 0. (If they really want to type a negative number, I think it will work anyway.)
=> Improve styling for sampling parameters.

functions/package-lock.json, functions/package.json, functions/src/api/model.response.ts, functions/src/api/ollama.api.test.ts, functions/src/api/ollama.api.ts, functions/src/api/openai.api.test.ts, functions/src/api/openai.api.ts
Add a unit test for the OpenAI API, using nock to mock out the API call. Also change the ollama unit test to use nock, so that it can run without a running ollama instance.
This also fixes a few minor errors in the two API implementations, that the tests caught.
=> Add unit test for OpenAI API.

frontend/src/components/experimenter/experimenter_data_editor.ts, frontend/src/components/stages/chat_editor.ts, functions/package-lock.json, functions/package.json, functions/src/agent.utils.ts, functions/src/api/gemini.api.ts, functions/src/api/model.response.ts, functions/src/api/ollama.api.test.ts, functions/src/api/ollama.api.ts, functions/src/api/openai.api.test.ts, functions/src/api/openai.api.ts, utils/src/experimenter.test.ts, utils/src/experimenter.ts
This also removes the llmType field in the Ollama API config.
Depends on #445.
=> Read model name from agent config in Gemini and Ollama APIs.

frontend/src/components/experiment_builder/agent_editor.scss, frontend/src/components/experiment_builder/agent_editor.ts, frontend/src/components/experiment_builder/experiment_builder.scss, frontend/src/components/experiment_builder/experiment_builder.ts, frontend/src/components/experiment_builder/experiment_settings_editor.ts, frontend/src/services/agent.editor.ts, frontend/src/services/experiment.manager.ts, frontend/src/shared/callables.ts, functions/src/agent.endpoints.ts, functions/src/agent.utils.ts, utils/src/agent.ts, utils/src/agent.validation.ts, utils/src/experimenter.test.ts, utils/src/experimenter.ts, utils/src/stages/chat_stage.ts
Note: Agent configs still in progress with fields subject to change.
This is not yet connected to actual experiment logic; rather, it enables us to edit and test new agent configs in the frontend experiment editor.
Fixes #418
=> Add new (refactored) agent configs and UI editor

functions/src/agent.utils.ts, functions/src/api/gemini.api.test.ts, functions/src/api/gemini.api.ts, functions/src/api/ollama.api.test.ts, functions/src/api/ollama.api.ts
Pass everything from AgentGenerationConfig through to the Gemini and Ollama APIs, except that frequency penalty and presence penalty aren't supported in Ollama.
Ollama puts some model parameters in a nested `options` field of the request body; for now, this doesn't support setting those, except for temperature and top_p.
Also fix a bug where agent.utils.ts wasn't calling into the Ollama API with the correct arguments.
This will have merge conflicts with the agent-refactor branch in progress.
=> Use sampler parameters for Gemini and Ollama APIs.

firestore/firestore.rules, frontend/src/components/experimenter/experimenter_panel.scss, frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/components/stages/chat_interface.ts, frontend/src/services/experiment.manager.ts, frontend/src/services/participant.service.ts, frontend/src/shared/callables.ts, frontend/src/shared/file.utils.ts, functions/src/alert.endpoints.ts, functions/src/index.ts, functions/src/stages/chat.endpoints.ts, utils/src/alert.ts, utils/src/alert.validation.ts, utils/src/index.ts
This sets up AlertMessage objects that can be written to collections both under participants (for the participant to view) and under the experiment (for the experimenter to view all alerts across all participants).
A participant submits an alert with a custom message (right now, the message is hardcoded in the frontend because alerts are currently only used in chat threads); since it is written both to the participant's alerts collection and the experiment alerts collection, the experimenter is able to view the new alert(s) (from a listener on the latter collection) in their experiment dashboard (via a new notifications panel). They can then mark the alert as read and send a custom response.
Note that right now, the alert message from the participant and responses from the experimenter …
=> Add alert system for participants to notify experimenters

frontend/src/components/stages/chat_editor.ts, frontend/src/components/stages/chat_interface.ts, frontend/src/services/participant.service.ts
- Hide agent generation config fields in chat editor if agent is from a pre-generationConfig experiment version
- In chat participant view, show all chat threads for experiments missing the currentDiscussionIndex field
- Fix readyToEndDiscussion logic to use publicStageData source of truth
=> Fix chat stage bugs involving agent editing and discussion threads

frontend/src/shared/file.utils.ts
Remove alphabetical sort, which put the chip negotiation players (which are actually already in order due to a turn/timestamp based sort earlier in the code) out of order, since their turn order in the chip game is not alphabetically determined.
=> Fix bug with sorting players in chip negotiation CSV

docs/changelog.md, frontend/src/components/experiment_builder/agent_editor.scss, frontend/src/components/experiment_builder/agent_editor.ts, frontend/src/components/experimenter/experimenter_panel.ts, frontend/src/sass/_common.scss, frontend/src/services/agent.editor.ts, frontend/src/services/agent.manager.ts, frontend/src/shared/games/reality_tv_chat.ts, functions/src/agent.utils.ts, functions/src/api/gemini.api.test.ts, functions/src/api/gemini.api.ts, functions/src/stages/chat.triggers.ts, functions/src/stages/chat.utils.ts, package-lock.json, package.json, utils/src/agent.ts, utils/src/experiment.ts, utils/src/experimenter.test.ts, utils/src/index.ts, utils/src/stages/chat_stage.prompts.ts, utils/src/stages/chat_stage.ts, utils/src/structured_output.test.ts, utils/src/structured_output.ts
This PR includes changes from PR #494 by @mkbehr, plus a few more.
Fixes #397:
- Experimenters can now configure custom schemas for structured outputs.
- Three special fields are supported: a field for the message, a field for whether or not to respond, and a field for an explanation or chain of thought. Experimenters can configure what these fields are named.
- The prompt will include a description of the output schema. Experimenters can disable this if they'd rather supply their own output examples.
- Experimenters can constrain the sampler to output valid json, or to output valid json in the specified schema. This is only supported for the Gemini API so far.
- Experiments with the old isJSON config should still work, but setting that config in new experiments is disabled.
- New …
=> Add structured output support for agents

functions/src/agent.utils.ts, functions/src/api/openai.api.test.ts, functions/src/api/openai.api.ts
Previously it was using the legacy text completions API. The chat completions API is needed to support structured output.
This doesn't segment the prompt into separate messages, it just sends the entire prompt as one user message, which should match the Gemini API behavior.
=> Move the openai-compatible API to the chat completions API.

functions/src/agent.endpoints.ts, functions/src/agent.utils.ts, functions/src/api/gemini.api.test.ts, functions/src/api/gemini.api.ts, functions/src/api/model.response.ts, functions/src/api/ollama.api.ts, functions/src/api/openai.api.ts, functions/src/stages/chat.triggers.ts, functions/src/stages/chat.utils.ts, functions/src/stages/ranking.utils.ts, functions/src/stages/survey.utils.ts
Restructure the ModelResponse interface to return error information.
- A new `status` field contains an enum to indicate whether the response was OK.
- `text` is populated only if the model returned a text response. (It will be empty for most error cases, but some errors will leave some text populated, like running out of output tokens.)
- A new `errorMessage` field contains the error message.
- A new `parsedResponse` field isn't populated yet, but it'll let us move structured output parsing closer to the model call, and return a parsing error if the model returns badly-formatted data.
Errors are reported through the prompt testing endpoint, but otherwise not used yet.
Only the Gemini API is fully supported so far. The OpenAI/compatible API will report UNKNOWN_ERROR for some errors, and …
=> Return detailed error output from Gemini API calls.

docs/developers/deploy.md, frontend/package-lock.json, frontend/package.json, frontend/webpack.config.ts
Fixes #525
This PR adds some fairly standard webpack cache-busting configuration, and docs explaining how to use it with firebase hosting (or the provider of your choice)
=> Cache busting for production deployments

frontend/src/components/participant_view/participant_nav.scss, frontend/src/components/popup/popup.scss, frontend/src/components/stages/chat_interface.scss, frontend/src/components/stages/chat_interface.ts, frontend/src/components/stages/chat_panel.scss, frontend/src/components/stages/chat_panel.ts, frontend/src/components/stages/stage_description.scss, frontend/src/components/stages/stage_description.ts, frontend/src/sass/_common.scss
Fixes #529
Adds some simple responsive layout to the participant view. On smaller screens:
- Hides the left sidebar showing the current stage
- Hides the left sidebar in the chat stage
- Shows chat participants and time remaining at the top of the window
- Puts the chat info inside the chat, so it scrolls off with new messages
- Reformats the buttons in the transfer popup
This code is a bit messy since I'm trying to get it out the door asap for an experiment we are running. But it does make participation possible on a phone. Especially, there is some duplicated code between `chat_panel` and `chat_interface` that could be refactored into a set of common components.
=> Responsive participant view

frontend/src/components/stages/survey_editor.scss, frontend/src/components/stages/survey_editor.ts, frontend/src/components/stages/survey_per_participant_view.ts, frontend/src/components/stages/survey_summary_view.ts, frontend/src/components/stages/survey_view.scss, frontend/src/components/stages/survey_view.ts, frontend/src/shared/games/lost_at_sea.ts, utils/src/stages/survey_stage.ts
Fixes #545.
* Extends `ScaleSurveyQuestion` to add a slider view. 
* This renders differently in the UI, otherwise uses the same base features and functions as the scale question. 
* Adds `middleText` option to `ScaleSurveyQuestion`.
* Adds `stepSize` option to `ScaleSurveyQuestion`.
* Adds visual editing of these properties to `survey_editor`.
* Updates `survey_summary_view` and `survey_per_participant_view` to account for slider.
=> Add slider scale option to survey questions

frontend/src/shared/games/chip_negotiation.ts, utils/src/stages/chip_stage.prompts.ts
- Add new survey stages, including pre-game, post-game, and role-specific feedback surveys
- Update two typos in chip negotiation prompts in the chip-assistance branch
- Add the additional instruction for AI assistance mode in chip-assistance branch
Checks:
=> Add survey stages to chip negotiation template

frontend/src/components/stages/flipcard_participant_view.ts
Re-add saveAndProgress (removed accidentally in #567). FlipCard stage has a custom SaveAndProgress:
```
private saveAndProgress = async () => {
if (!this.stage) return;
await this.participantAnswerService.saveFlipCardAnswers(this.stage.id);
await this.participantService.progressToNextStage();
};
```
=> Re-add saveAndProgress in FlipCard (removed accidentally in #567).

frontend/src/components/stages/chip_participant_view.ts, functions/src/stages/chip.endpoints.ts, functions/src/stages/chip.utils.ts, utils/src/stages/chip_stage.ts
1. Change the ProposedTime Variable, Only update LLM-related fields if response was successful
2. Add the new Error mode to [utils/src/stages/chip_stage.ts](https://github.com/PAIR-code/deliberate-lab/pull/590/files#diff-91e877b3324e78c1e3dccc27dd4126f8a69bb1329b0b2b25bde83f448857c3b7)
3. In [chip_participant_view.ts](https://github.com/PAIR-code/deliberate-lab/pull/590/files#diff-243102fee910e9b77581ed63fe61e78dd33c318c11effbae8e09ee282bf0ff39), added the error mode and check if the LLM query response is not valid, render the error mode
=> Add retry and fallback logic to chip assistance

frontend/src/shared/templates/chip_negotiation.ts, functions/src/stages/chip.utils.ts, utils/src/stages/chip_stage.prompts.ts
- update instrcution and term of service in chip-pilot branch
- update the prompt for giving feedbacks
- revert structured output change
=> Update instruction and term of service for chip negotiation template

frontend/src/components/stages/chip_participant_view.ts, frontend/src/shared/templates/chip_negotiation.ts, functions/src/stages/chip.endpoints.ts, utils/src/stages/chip_stage.prompts.ts
1. Add the default response when requested > current in chip-pilot, I have updated the chip.endpoint.ts
=> Add default "false" response when offer cannot be accepted in chip assistance

.github/workflows/ci.yaml
This way the tests will still run if the formatting fails.
=> Split CI into separate jobs for format and test

frontend/src/components/experiment_builder/agent_chat_prompt_editor.scss, frontend/src/components/experiment_builder/agent_chat_prompt_editor.ts, frontend/src/components/experiment_builder/structured_prompt_editor.scss, frontend/src/components/experiment_builder/structured_prompt_editor.ts, functions/src/prompt.utils.ts, utils/src/structured_prompt.ts
This creates `PromptItemGroup` type, which is a list of `PromptItem`s. PromptItemGroups are parsed/generated recursively when creating prompts. Prompt Groups have titles, but, they are only used in the editor UI. Otherwise, Prompt Groups are themselves just PromptItems. 
This feature will allow for shuffling of prompt items within groups (to come in a follow-up PR).
Core `PromptItemGroup` functionality:
* `renderPromptItem` -> `renderPromptItems`: Mostly the same except now maps `renderPromptItem` content to a list of all `PromptItem`s.
* `renderItemEditor`: Added `PromptItemType.GROUP` case
* Added `renderPromptItemGroupEditor`
Related changes / refactors in `structured_prompt_editor.ts`:
* `<Add/Delete/Move>PromptItem`: Takes a `TargetArray` to operate on -- this allows the editor to …
=> Added prompt group functionality.

frontend/src/components/experiment_builder/agent_chat_prompt_editor.ts, frontend/src/components/experiment_builder/structured_prompt_editor.scss, frontend/src/components/experiment_builder/structured_prompt_editor.ts, functions/src/prompt.utils.ts, utils/src/structured_prompt.ts, utils/src/utils/random.utils.ts
Follow-up to #622 -- adds the ability to shuffle `PromptItemGroup`s based on experiment ID, cohort ID, participant ID, or a custom seed string.
(Need to rebase after #622 is merged)
=> Add shuffling to PromptItemGroups.

frontend/src/components/experiment_builder/agent_chat_prompt_editor.ts, frontend/src/components/experiment_builder/agent_persona_editor.ts, frontend/src/components/experiment_builder/experiment_builder.scss, frontend/src/components/experiment_builder/experiment_builder.ts, frontend/src/components/experiment_builder/experiment_settings_editor.ts, frontend/src/components/experimenter/experimenter_data_editor.ts, frontend/src/components/header/header.scss, frontend/src/components/header/header.ts, frontend/src/components/stages/base_stage_editor.scss, frontend/src/components/stages/base_stage_editor.ts, frontend/src/components/stages/group_chat_editor.scss, frontend/src/components/stages/group_chat_editor.ts, frontend/src/components/stages/private_chat_editor.ts, frontend/src/components/stages/transfer_editor.scss, frontend/src/components/stages/transfer_editor.ts, frontend/src/sass/_common.scss, frontend/src/services/experiment.editor.ts, utils/src/agent.ts
- Update experiment editor nav to contain single, more granular menu of panel options (with sub-settings, e.g., agent persona configs, hidden inside panels)
- Use tabs inside of stage editors to set metadata vs. progress vs. stage-specific settings
- Show errors when creating experiment (e.g., if name is missing, no stages have been added)
- Add description field to agent persona configs
- Show agent mediator previews in group/private chat stage settings
- Only show "alpha mode" features if additional setting (in experiment editor) is checked
Fixes #626
=> Update experiment editor UI with streamlined nav, tabs for stage settings, alpha mode tags

.github/workflows/ci.yaml, functions/firebase-test.json, functions/package.json, functions/src/log.utils.test.ts
Moving #635 to the main branch.
I had a Firestore emulator already running when I was developing locally, and the test doesn't work without one.
Configure package.json to wrap this test with a firebase command to run a temporary emulator on port 8081, and check the FIRESTORE_EMULATOR_HOST environment variable it sets. Fall back to port 8080 otherwise. This way `npm test` will work whether or not an emulator is running locally, and `npx jest` will work if an emulator is running locally.
=> Run log.utils.test.ts with Firestore emulator.

frontend/src/components/participant_view/participant_header.ts
This clarifies that the info popup refers to the stage itself, rather than containing global or user-related info.
https://screenshot.googleplex.com/AKyiMLrA7c5ihj2
Fixes #696
=> Left aligns info icon to be right next to the stage name
